server:
   port: 8000
spring:
   application:
      name: app-wfaceboss-member
#eureka:
eureka:
###集群地址
   client:
      service-url:
         defaultZone: http://localhost:8100/eureka, http://localhost:8200/eureka
###需要将我的服务注册到注册中心
         register-with-eureka: true
###是否需要从eureka上获取注册信息（需要检索服务）
         fetch-registry: true